// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import Admin__MarkdownEditorController from './admin/markdown_editor_controller';
application.register('admin--markdown-editor', Admin__MarkdownEditorController);

import Admin__ProductBehavioursController from './admin/product_behaviours_controller';
application.register('admin--product-behaviours', Admin__ProductBehavioursController);

import Admin__ProductSeatCategoryInputController from './admin/product_seat_category_input_controller';
application.register('admin--product-seat-category-input', Admin__ProductSeatCategoryInputController);

import Admin__ProductToAndFromProductInputController from './admin/product_to_and_from_product_input_controller';
application.register('admin--product-to-and-from-product-input', Admin__ProductToAndFromProductInputController);

import Admin__SeatmapController from './admin/seatmap_controller';
application.register('admin--seatmap', Admin__SeatmapController);

import Admin__SidebarController from './admin/sidebar_controller';
application.register('admin--sidebar', Admin__SidebarController);

import Admin__TournamentFormController from './admin/tournament_form_controller';
application.register('admin--tournament-form', Admin__TournamentFormController);

import AlertController from './alert_controller';
application.register('alert', AlertController);

import ButtonController from './button_controller';
application.register('button', ButtonController);

import CocoonController from './cocoon_controller';
application.register('cocoon', CocoonController);

import ImageCropperController from './image_cropper_controller';
application.register('image-cropper', ImageCropperController);

import ToggleablePasswordController from './toggleable_password_controller';
application.register('toggleable-password', ToggleablePasswordController);
