require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/schema.rb'
    - 'locale/model_attributes.rb'
    - 'node_modules/**/*'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
  NewCops: enable
  SuggestExtensions: false

# General cops
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/SignalException:
  EnforcedStyle: only_fail

Style/ConditionalAssignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

# Rails cops
Rails/BulkChangeTable:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Naming/VariableNumber:
  EnforcedStyle: snake_case
  # Sometimes we need different cases in haml files, e.g. for the `html5` argument
  Exclude:
    - 'app/views/**/*'

# Disable for test files
Metrics/ClassLength:
  Exclude:
    - test/**/*
  Max: 150

Metrics/ModuleLength:
  Exclude:
    - test/**/*
  Max: 150

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Rails/ActionControllerFlashBeforeRender:
  Enabled: false

Rails/ActionOrder:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

# Does not work in haml files
Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'app/views/**/*'

Rails/ThreeStateBooleanColumn:
  # Ignore the already existing migrations, as we fix this in a
  # new migration, such that the existing migrations remain unchanged
  Exclude:
    - db/migrate/20210524120137_add_otp_secret_key_to_users.rb
    - db/migrate/20211220111608_create_pages.rb
    - db/migrate/20220924131014_add_devise_two_factor_to_users.rb