version: '3.0'

services:
  db:
    image: postgres:15.1-alpine
    hostname: ${POSTGRES_HOSTNAME:-db}
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-l4n}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
  web:
    image: l4n
    command: bash -c "rails db:migrate && rails s -p 3000 -b '0.0.0.0'"
    networks:
      - reverse_proxy
      - default
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # Set defaults for running server
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: true
      # Database
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_USER: ${POSTGRES_USER:-l4n}
      # Mailer
      HOST_DOMAIN: ${HOST_DOMAIN:-localhost}
      USE_SMTP: ${USE_SMTP:-false}
      # ActiceRecord encryption
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?err}
      AR_PRIMARY_KEY: ${AR_PRIMARY_KEY:?err}
      AR_DETERMINISTIC_KEY: ${AR_DETERMINISTIC_KEY:?err}
      AR_KEY_DERIVATION_SALT: ${AR_KEY_DERIVATION_SALT:?err}
      # Securing the registration
      HCAPTCHA_SITE_KEY: ${HCAPTCHA_SITE_KEY:?err}
      HCAPTCHA_SITE_SECRET: ${HCAPTCHA_SITE_SECRET:?err}
      # Gameaccounts
      STEAM_WEB_API_KEY: ${STEAM_WEB_API_KEY:?err}
      DISCORD_ID: ${DISCORD_ID:?err}
      DISCORD_SECRET: ${DISCORD_SECRET:?err}
      DISCORD_BOT_AUTH: ${DISCORD_BOT_AUTH:?err}
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverse_proxy
      - traefik.http.routers.${ROUTER_NAME:-l4n}.rule=Host(`${HOST_DOMAIN:?err}`)
      - traefik.http.routers.${ROUTER_NAME:-l4n}.tls.certresolver=letsencrypt
volumes:
  db-data:
networks:
  reverse_proxy:
    name: reverse_proxy