default: &default
  adapter: postgresql
  host: localhost
  username: rails
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: l4n

test:
  <<: *default
  database: l4n_test

production:
  <<: *default
  host: <%= ENV['POSTGRES_HOSTNAME'] %>
  database: l4n_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
